services:

  chat-streamlit:
    image: chat-streamlit:latest
    container_name: chat-streamlit
    ports:
      - "8501:8501"
    restart: on-failure

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.1
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - ./weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'

  chat-django:
    image: chat-django:latest
    container_name: chat-django
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - weaviate
